# Autogenerated wrapper script for blake3_jll for aarch64-apple-darwin
export libblake3

JLLWrappers.@generate_wrapper_header("blake3")
JLLWrappers.@declare_library_product(libblake3, "@rpath/libblake3.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libblake3,
        "lib/libblake3.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
