# Autogenerated wrapper script for blake3_jll for armv6l-linux-gnueabihf
export libblake3

JLLWrappers.@generate_wrapper_header("blake3")
JLLWrappers.@declare_library_product(libblake3, "libblake3.so.0")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libblake3,
        "lib/libblake3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
