# Autogenerated wrapper script for blake3_jll for x86_64-w64-mingw32
export libblake3

JLLWrappers.@generate_wrapper_header("blake3")
JLLWrappers.@declare_library_product(libblake3, "libblake3.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libblake3,
        "bin\\libblake3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
